---
title: "Parallel programming"
author: 
  - name: Stephanie Hicks
    url: https://stephaniehicks.com
    affiliation: Department of Biostatistics, Johns Hopkins
    affiliation_url: https://publichealth.jhu.edu
description: "and dealing with large data..."
draft: true
---

# Pre-lecture activities

::: callout-tip

In advance of class, please install

- [`future`](https://CRAN.R-project.org/package=future) - this provides a unified parallel framework in R consistent

In addition, please read through

- [Strategies for dealing with large data](../../readings/11-strategies-big-data/index.qmd)
- <https://www.futureverse.org/packages-overview.html> (just the `future` R package)

:::



::: callout-note

## How much should I prepare for before class?

You should have `future` installed and be familiar with the three basic functions - `plan()`, `future()`, and `value()`. 

We will learn more about these functions in class. 


:::


# Lecture 

## Acknowledgements

Material for this lecture was borrowed and adopted from

- <https://www.futureverse.org/packages-overview>

## Learning objectives

::: callout-note
### Learning objectives

**At the end of this lesson you will:**

- Understand the basics of parallel computing
- Become familiar with basic functions in the `future` package
- Recognize different file formats to work with large data not locally
- Implement three ways to work with large data: 
  1. "sample and model" 
  2. "chunk and pull"
  3. "push compute to data"

:::

## Slides 

- [Lecture 10: Parallel computing (and dealing with large data)]()


# Class activity 

For the rest of the time in class, you and your team will work on the final project. Stephanie will walk around to answer questions and happy to help in any way! 

# Post-lecture

If you would like more practice using the `future` package, there are two 
tutorials for you to work through own your own developed by Henrik Bengtsson 
from the UseR! 2024 conference: 

- [Lab: Futureverse 1](https://henrikbengtsson.github.io/future-tutorial-user2024/lab1.html)
- [Lab: Futureverse 2](https://henrikbengtsson.github.io/future-tutorial-user2024/lab2.html)